name: Upload Amazon Images
permissions:
  contents: read
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build-ami:
    name: Upload Amazon Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        release:
          - release-24.05
        # - nixos-unstable
        system:
          - x86_64-linux
        #- aarch64-linux
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          flakehub: true

      # note: no magic-nix-cache. The build is nearly trivial, except for the gigantic disk image at the end.
      # No need to cache that monstrosity.

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::535002876703:role/upload-ami
          aws-region: us-east-2

      - run: nix build -L .#diskImages.x86_64-linux.aws

      - name: Upload Smoke test AMI
        id: upload_smoke_test_ami
        run: |
          image_ids=$(nix run github:NixOS/amis#upload-ami -- \
              --image-info "./result/nix-support/image-info.json" \
              --prefix "smoketest/" \
              --s3-bucket "detsys-nixos-images-20240916205705854200000001" \
              --run-id "${GITHUB_RUN_ID}")
          echo "image_ids=$image_ids" >> "$GITHUB_OUTPUT"

      - name: Smoke test
        id: smoke_test
        # NOTE: make sure smoke test isn't cancelled. Such that instance gets cleaned up.
        run: |
          image_ids='${{ steps.upload_smoke_test_ami.outputs.image_ids }}'
          image_id=$(echo "$image_ids" | jq -r '.["us-east-2"]')
          nix run github:NixOS/amis#smoke-test -- --image-id "$image_id"

      - name: Clean up smoke test
        if: ${{ cancelled() }}
        run: |
          image_ids='${{ steps.upload_smoke_test_ami.outputs.image_ids }}'
          image_id=$(echo "$image_ids" | jq -r '.["us-east-2"]')
          nix run github:NixOS/amis#smoke-test -- --image-id "$image_id" --cancel
      - name: Upload AMIs to all available regions
        if: github.ref == 'refs/heads/main'
        run: |
          nix run github:NixOS/amis#upload-ami -- \
              --image-info "./result/nix-support/image-info.json" \
              --prefix "determinate/nixos/" \
              --s3-bucket "detsys-nixos-images-20240916205705854200000001" \
              --run-id "${GITHUB_RUN_ID}" \
              --copy-to-regions \
              --public
