name: Upload Amazon Images
permissions:
  contents: read
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build-ami:
    name: Upload Amazon Image
    runs-on: ${{ matrix.system == 'x86_64-linux' && 'ubuntu-latest' || 'UbuntuLatest32Cores128GArm' }}
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        system:
          - aarch64-linux
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          flakehub: true
          extra-conf: |
            extra-system-features = kvm

      # note: no magic-nix-cache. The build is nearly trivial, except for the gigantic disk image at the end.
      # No need to cache that monstrosity.

      - run: sudo -i bash -c 'apt install systemd-coredump; echo ProcessSizeMax=10G >> /etc/systemd/coredump.conf; systemctl daemon-reload; systemctl restart systemd-coredump.socket'

      - id: build_disk_image
        run: |
          nix build -L .#"diskImages.${{ matrix.system }}.aws"
          suffix=$(readlink ./result | cut -d'/' -f4 | cut -d'-' -f1)
          echo "suffix=$suffix" >> "$GITHUB_OUTPUT"

      - name: Upload Smoke test AMI
        id: upload_smoke_test_ami
        run: |
          nix build github:NixOS/amis#upload-ami

      - name: Breakpoint if tests failed
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: edolstra, grahamc
