name: Update Flake Lock

permissions:
  contents: read

on:
  schedule:
  - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update-flake-lock:
    name: Update Flake Lock
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/update-flake-lock@main
